strategy:
  rsi_period: 10
  rsi_oversold: 35
  rsi_overbought: 65
  confirmation_bars: 3
  atr_period: 14
  extended_debug: true
  rsi_delta: 5
  short_delta: 10
  debug_frequency: 50

risk_management:
  risk_pct: 0.2
  k_atr: 1.5
  m_atr: 3.0
  atr_period: 14
  cooldown_bars: 2

trading:
  symbol: "BTC/USDT"
  timeframe: "1h"
  higher_timeframe: "1d"

binance:
  api_key: ed7f77b2127781dc090c9d2c04e73740eb11f9e3ebb257088003e607b325037d
  secret: 9c18a13451aa73a110154af79b917122b30350d9f608933e07fd1f6bcc70252b
