strategy:
  rsi_period: 5                 # Bestes Ergebnis: 5 statt 10
  rsi_overbought: 60            # Bestes Ergebnis: 60 statt 65
  rsi_oversold: 36              # Bestes Ergebnis: 36 statt 35
  confirmation_bars: 1          # Bestes Ergebnis: 1
  atr_period: 14                # Bleibt unverändert
  ema_period: 50                # Bleibt unverändert
  volume_filter: true           # Bleibt unverändert
  # Individuelle Volume Thresholds:
  volume_thresholds:
    BTCUSDT: 1000
    ETHUSDT: 500
    BNBUSDT: 300
  extended_debug: true          # Bleibt unverändert

risk_management:
  risk_pct: 0.017               # Bestes Ergebnis: ca. 0.017 (1,7% Risiko)
  k_atr: 1.98                   # Bestes Ergebnis: ca. 1.98
  m_atr: 2.73                   # Bestes Ergebnis: ca. 2.73
  atr_period: 14                # Bleibt unverändert
  cooldown_bars: 4              # Bestes Ergebnis: 4 (statt 2)
  short_tp_multiplier: 1.98      # Bestes Ergebnis: ca. 1.98

trading:
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
  timeframe: "1h"
  higher_timeframe: "1d"
  use_testnet: true  # Testnet aktivieren (false = Live-Modus)
  trade_pair: "BTCUSDT"  # Standard-Handelspaar
  leverage: 10  # Hebel
