platforms:
  binance: true
  metatrader: true

strategy:
  rsi_period: 2
  rsi_overbought: 87
  rsi_oversold: 38
  atr_period: 14
  lookback: 3
  volume_filter: false
  volume_threshold: null
  volume_lookback: 10
  volume_weight: 0.5
  gap_threshold: 0.005
  gap_block_hours: 4
  extended_debug: true
  atr_tp_multiplier: 6.0
  atr_sl_multiplier: 1.5

risk_management:
  initial_balance: 16000
  base_risk: 0.01
  dynamic_risk_factor: 0.001
  atr_period: 14
  cooldown_bars: 4
  short_tp_multiplier: 1.98

trading:
  max_open_positions: 3
  binance:
    symbols:
      BTCUSDT:
        atr_sl_multiplier: 1.2
        atr_tp_multiplier: 6.5
      ETHUSDT:
        atr_sl_multiplier: 2.5
        atr_tp_multiplier: 6.0
      BNBUSDT:
        atr_sl_multiplier: 2.5
        atr_tp_multiplier: 8.0
    timeframe: "1h"
    higher_timeframe: "4h"
    use_testnet: true
    leverage: 1
    volume_column: "volume"
  metatrader:
    symbols:
      EURUSD:
        atr_sl_multiplier: 0.7
        atr_tp_multiplier: 4.0
      GBPUSD:
        atr_sl_multiplier: 0.7
        atr_tp_multiplier: 4.0
      USDJPY:
        atr_sl_multiplier: 0.7
        atr_tp_multiplier: 4.0
      AUDUSD:
        atr_sl_multiplier: 0.7
        atr_tp_multiplier: 4.0
    timeframe: "H1"
    higher_timeframe: "H4"
    leverage: 1
    volume_column: "tick_volume"

tuning:
  atr_sl_multiplier_range: [0.5, 2.0, 0.1]
  atr_tp_multiplier_range: [4.0, 8.0, 0.5]
  output_path: "results/tuning/best_params.yaml"