platforms:
  binance: false
  metatrader: true

strategy:
  rsi_period: 5
  rsi_overbought: 60
  rsi_oversold: 36
  confirmation_bars: 1
  atr_period: 14
  ema_period: 50
  volume_filter: true
  volume_thresholds:
    BTCUSDT: 1000
    ETHUSDT: 500
    BNBUSDT: 300
  extended_debug: true

risk_management:
  risk_pct: 0.017
  k_atr: 1.98
  m_atr: 2.73
  atr_period: 14
  cooldown_bars: 4
  short_tp_multiplier: 1.98

trading:
  binance:
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
    timeframe: "1h"
    higher_timeframe: "1d"
    use_testnet: true
    trade_pair: "BTCUSDT"
    leverage: 10
  metatrader:
    symbol: "EURUSD"
    timeframe: "H1"
    higher_timeframe: "D1"
    leverage: 1
