platforms:
  binance: false
  metatrader: true

strategy:
  rsi_period: 2
  rsi_overbought: 87
  rsi_oversold: 38
  atr_period: 14
  lookback: 3
  volume_filter: false
  volume_threshold: null
  volume_lookback: 10
  volume_weight: 0.5
  gap_threshold: 0.005
  gap_block_hours: 4
  extended_debug: true
  atr_tp_multiplier: 6.0
  atr_sl_multiplier: 1.5

risk_management:
  initial_balance: 16000  # Budget des Demo-Accounts
  risk_pct: 0.01  # 1 % Risiko pro Trade
  k_atr: 1.98
  m_atr: 2.73
  atr_period: 14
  cooldown_bars: 4
  short_tp_multiplier: 1.98

trading:
  max_open_positions: 3
  binance:
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
    timeframe: "1h"
    higher_timeframe: "1d"
    use_testnet: true
    trade_pair: "BTCUSDT"
    leverage: 1
    volume_column: "volume"
  metatrader:
    symbol: "EURUSD"
    timeframe: "H1"
    higher_timeframe: "H4"
    leverage: 1
    volume_column: "tick_volume"