platforms:
  binance: false
  metatrader: true

strategy:
  rsi_period: 5
  rsi_overbought: 75
  rsi_oversold: 25
  atr_period: 14
  lookback: 5  # Für Gradienten-Trendbestimmung
  volume_filter: false
  volume_threshold: null
  extended_debug: true
  atr_tp_multiplier: 5.0
  atr_sl_multiplier: 1.5

risk_management:
  risk_pct: 0.017
  k_atr: 1.98
  m_atr: 2.73
  atr_period: 14
  cooldown_bars: 4
  short_tp_multiplier: 1.98

trading:
  max_open_positions: 3
  binance:
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
    timeframe: "1h"
    higher_timeframe: "1d"
    use_testnet: true
    trade_pair: "BTCUSDT"
    leverage: 10
    volume_column: "volume"
  metatrader:
    symbol: "EURUSD"
    timeframe: "H1"
    higher_timeframe: "H4"
    leverage: 1
    volume_column: "tick_volume"